name: Compile Paper

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: paper.tex
      
      - uses: actions/upload-artifact@v3
        with:
          name: Paper PDF
          path: paper.pdf
